name: ğŸš€ Deploy Microservices to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy-to-ecs:
    name: ğŸ” ECS Deployment
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ”„ Checkout repo
        uses: actions/checkout@v3

      - name: ğŸ” Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # # --- Auth Service ---
      # - name: ğŸš€ Deploy auth-service to ECS
      #   run: |
      #     aws ecs update-service \
      #       --cluster ecommerce-cluster \
      #       --service auth-service \
      #       --force-new-deployment

      # --- User Service ---
      - name: ğŸš€ Deploy user-service to ECS
        run: |
          aws ecs update-service \
            --cluster ecommerce-cluster \
            --service backend-user-service \
            --force-new-deployment

      # --- Product Service ---
      - name: ğŸš€ Deploy product-service to ECS
        run: |
          aws ecs update-service \
            --cluster ecommerce-cluster \
            --service backend-product-service-task-service \
            --force-new-deployment

      # --- Order Service ---
      - name: ğŸš€ Deploy order-service to ECS
        run: |
          aws ecs update-service \
            --cluster ecommerce-cluster \
            --service backend-order-service-task-service \
            --force-new-deployment

      # # --- Cart Service ---
      # - name: ğŸš€ Deploy cart-service to ECS
      #   run: |
      #     aws ecs update-service \
      #       --cluster ecommerce-cluster \
      #       --service cart-service \
      #       --force-new-deployment

      # --- Inventory Service ---
      - name: ğŸš€ Deploy inventory-service to ECS
        run: |
          aws ecs update-service \
            --cluster ecommerce-cluster \
            --service backend-inventory-service-task-service \
            --force-new-deployment

      # # --- Payment Service ---
      # - name: ğŸš€ Deploy payment-service to ECS
      #   run: |
      #     aws ecs update-service \
      #       --cluster ecommerce-cluster \
      #       --service payment-service \
      #       --force-new-deployment

      # # --- API Gateway ---
      # - name: ğŸš€ Deploy api-gateway to ECS
      #   run: |
      #     aws ecs update-service \
      #       --cluster ecommerce-cluster \
      #       --service api-gateway \
      #       --force-new-deployment
